In [34]:
import numpy as np

def Lagrange(x,y,z):  #  定义拉格朗日插值多项式
    sum=[ ]
    n = len(x)
    m = len(z)
    for j in range(m):
        la=0
        for k in range(n):
            
            def L(k):   # 定义嵌套函数l_k(x)  
                t=1
                for i in range(n):
                    if i!=k:
                        t=t*(z[j]-x[i])/(x[k]-x[i])
                    else:
                        t=t
                return t
            
            la=la+y[k]*L(k)
            
        sum.append(la)
        
    return sum

def fl(x, y, z):
    n = len(x)
    X = x.reshape(-1, 1) - x
    idx = np.arange(n)
    X[idx, idx] = 1
    l0 = X.prod(axis=1)
    S = z.reshape(-1, 1) - x
    S = np.repeat(s, n, axis=0).reshape(-1, n, n)
    S[:, idx, idx] = 1
    l1 = S.prod(axis=-1)
    f = np.sum(l1/l0*y, axis=-1)
    return f

In [42]:
x = np.array([0.32,0.34,0.36])
y = np.array([0.314567,0.333487,0.352274])
n = len(x)
z = np.array([0.33, 0.35])

In [38]:

print(X)

[[ 1.   -0.02 -0.04]
 [ 0.02  1.   -0.02]
 [ 0.04  0.02  1.  ]]


In [39]:
l0 = X.prod(axis=1)
print(l0)

[ 0.0008 -0.0004  0.0008]


In [40]:
s = z.reshape(-1, 1) - x
n = len(x)
s = np.repeat(s, n, axis=0).reshape(-1, n, n)
s[:, idx, idx] = 1
l1 = s.prod(axis=-1)
f = np.sum(l1/l0*y, axis=-1)
print(f)


[ 0.32404363  0.34289712]


In [44]:
Lagrange(x,y,z)

[0.324043625, 0.34289712499999991]

In [43]:
Lagrange(x,y,z)

[0.324043625, 0.34289712499999991]